version: '3.4'

services:
    api:
        build: 
            context: .
            target: development
        restart: on-failure
        user: root
        stdin_open: true
        tty: true
        volumes: 
            - .:/app
        ports: 
            - 80:80
