name: "Excellent CI/CD"

on:
    push:
        branches:
        - main

jobs:
    build:
        name: "Build and push to CR"
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Login to GAR
          uses: docker/login-action@v2
          with:
              registry: europe-west4-docker.pkg.dev
              username: _json_key
              password: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Setup Google CLI
          uses: google-github-actions/setup-gcloud@v0

        - name: Build and Push Image
          uses: docker/build-push-action@v2
          with:
              push: true
              tags: |
                  europe-west4-docker.pkg.dev/excellent-366409/excellent/main:latest
        
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        needs: [build]

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Setup
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Plan
          run: terraform plan
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          run: terraform apply -auto-approve
          env: 
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
