name: "Excellent CI/CD"

on:
    push:
        branches:
        - main

jobs:
    build:
        name: "Build and push to CR"
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Google Auth
          uses: 'google-github-actions/auth@v0'
          with:
               credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Setup Google CLI
          uses: google-github-actions/setup-gcloud@v0

        - name: Build Image
          run: |-
              docker build -t eu.gcr.io/excellent-366409:$GITHUB_SHA .

        - name: Configure Docker
          run: |
              gcloud auth configure-docker europe-west4-docker .pkg.dev

        - name: Push Image
          run: |-
              docker push europe-west4-docker.pkg.dev/excellent-366409/excellent/main:$GITHUB_SHA
        
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        needs: [build]

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Setup
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Plan
          run: terraform plan
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          run: terraform apply -auto-approve
          env: 
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
