name: "Excellent CI/CD"

on:
    push:
        branches:
        - main

jobs:
    build:
        name: "Build and push to CR"
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Google CLI
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
          with:
            service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
            project_id: "excellent-366409"
            export_default_credentials: true

        - name: Build Image
          run: |-
              docker build -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

        - name: Configure Docker
          run: |
              gcloud auth configure-docker -q

        - name: Push Image
          run: |-
              docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Setup
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Plan
          run: terraform plan
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          run: terraform apply -auto-approve
          env: 
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
